@tag.header()
	
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

		<div class="row justify-content-md-center">
		    <div class="col-md-2 col-xs-6">
		      <a href="{{url_for('create')}}" class="btn btn-success">Crear Cliente</a>
		    </div>
		    <div class="col-md-2 col-xs-6">
		      <a href="{{url_for('create')}}" class="btn btn-success">Crear Empleado</a>
		    </div>
	  	</div>


@tag.footer()
