@tag.header()
	
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

		<div class="row justify-content-md-center">
		    <div class="col-md-2 col-xs-6">
		      <a href="/crearPicole" class="btn btn-success">Picole</a>
		    </div>
		    <div class="col-md-2 col-xs-6">
		      <a href="/crearBombon" class="btn btn-success">Bombon</a>
		    </div>
	  	</div>


@tag.footer()