@tag.header()
	
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

        <br>
		<div class="row justify-content-md-center">
		    <div class="col-md-2 col-xs-6">
		      <a href="/jornaleros" class="btn btn-success">Jornaleros</a>
		    </div>
		    <div class="col-md-2 col-xs-6">
		      <a href="/repartidores" class="btn btn-success">Repartidores</a>
		    </div>
	  	</div>


@tag.footer()
