<!doctype html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>Heladeria</title>
    </head>
    <br>
        <br>
            <br>
                <br>
                    <br>
                        <br>
                            <br>
                                <br>
                                    <br>
    <body>
        <main role="main" class="container my-auto">
            <div class="row">
                <div id="login" class="col-lg-4 offset-lg-4 col-md-6 offset-md-3
                    col-12">
                    <h5 class="text-center">Bienvenido de nuevo</h5>
                    <h2 class="text-center">Ingrese en el sistema</h2>
                    <form>
                        <div class="form-group">
                            <label for="Nombre">Nombre</label>
                            <input id="Nombre" name="Nombre"
                                class="form-control" type="nombre"
                                placeholder="Nombre de usuario">
                        </div>
                        <br>
                        <div class="form-group">
                            <a href="/index" class="btn btn-success">Ingresar</a>
                        </div>
                        <br>
                    </form>
                </div>
            </div>
        </main>

@tag.footer()

