@tag.header()
	
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

		<div class="row justify-content-md-center">
		    <div class="col-md-2 col-xs-6">
		      <a href="/jornalero/nuevo" class="btn btn-success">Jornalero</a>
		    </div>
		    <div class="col-md-2 col-xs-6">
		      <a href="/repartidor/nuevo" class="btn btn-success">Repartidor</a>
		    </div>
	  	</div>


@tag.footer()