        
        <script src="/Bootstrap/js/jquery-3.0.0.slim.min.js"></script>
        <script src="/Bootstrap/js/bootstrap.bundle.min.js"></script>
        
        <!--
        Intento de usar webjars (error 404, recurso no encontrado)
        <script src="/webjars/jquery/jquery-3.0.0.slim.min.js"></script>
        <script src="/webjars/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
        -->
    </body>
</html>